write_dad_joke:
  description: >
    Write a dad joke about {topic}.
    Ensure the joke is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A funny dad joke about {topic}, with exactly {sentence_count} sentences.
  agent: joke_writer
